### ISSUE TITLE
Idea for displaying multiple recorded files

### ISSUE THREAD

**Issue by collectorgeneral** [y20k/trackbook#10]
Now that displaying last recorded track is more or less fully functional, we can perhaps proceed to implementing full fledged history display. 
I remember somewhere you said you were first going to display a few files at a time. I was thinking about it yesterday, I think there is a simpler way to do an arbitrary number of files. We know that all files are stored under Android/data/org.y20k.trackbook/*.trackbook. Why not pull up a list of files, put them in a variable and load the current file to display? 
As an example, on a shell I know I would type `ls /Android/data/org.y20k.trackbook/*.trackbook` and this will give the list of files that can be read by trackbook. You can pull this list (use `trim()` if necessary) and cycle through the list when the user wants to go to the previous or next track. The list *may* have to be updated everytime the 'History' tab is opened. 
as an example, I know doing this is pretty simple on something like Python, you call the function to get the list of files, store the results in a list, and allocate a variable to keep the current index(can always start at 0) and just `load(file_list([ind]))`. Everytime user presses back or forward, increment/decrement index as required and load() again. You can wrap around/disable the buttons if `ind<0 or ind>len(file_list)`. This does not really require you do manually keep a track of EVERY track ever recorded, because the list is generated dynamically. Due to generating list of files dynamically, this method can also avoid circumstances where user moves new tracks in/moves old tracks out for backup purposes. 
However I *could* vastly be underestimating the requirements for Android, if that is the case do let me know! 
As for how to provide an interface to actually allow the said cycling, to keep things simple, you could just put two buttons on the top or bottom (like `<<` `>>` or `Prev Track` `Next Track`) that will allow users to move forward or backward. Edit: Alternatively, you could show a dropdown list of the all files where the user can tap any file they want and load that file. 
Of course, all this at your own time 😄 . As usual, do not hesitate to release beta apks for me to break and annoy you with 😆

**Comment by y20k** [comment]
Thanks for your input!! A history of tracks is the next thing - after I get the 1.0 published. As for your suggestions. The app has a method to get all the .trackbook-files from storage. I need (1) a way to select the recording, I want to display (UI), and (2) a way to store the state (which one was selected), since the UI gets killed all the time. I think that should be not too hard. (knock on wood ;-) )

As for the UI (1). I was thinking of a dropdown menu. But I am not sure. I want the user to be able to delete a track, too.

**Comment by collectorgeneral** [comment]
@y20k I agree with the dropdown, it occured to me that it would probably be a better way to display stuff. As for the saving state part, I had not thought of it. I just assumed that everytime the user opens the 'History', the list gets repopulated and the latest file gets displayed first. From there the user can pick the file they wish to see. (You may already be aware of this, but just for the sake of info, keep in mind that the users can add or remove tracks from the directory, so ideally you would want to re-populate the list of .*trackbook files everytime the 'History' tab is open, and then display the current.)
However if you think having a save state is a simple enough idea to implement, then by all means do go ahead 😄 .

**Comment by y20k** [comment]
This is how I imagine the track selection will work:

![idea](https://cloud.githubusercontent.com/assets/9103935/22329010/94646052-e3bf-11e6-9b3b-ec826841238c.png)

Obviously the font color needs to change and instead of a file name a more human readable text should be displayed. The screenshot is not a mockup, but code running in an emulator. But it is just the UI. The code does nothing but display a list of .trackbook-files a user has.

**Comment by collectorgeneral** [comment]
I think that's brilliant!
Yes font can probably be white, will go well with the rest of the app.
Name, I think its fine. The filename format for the tracks currently is the best way to do it. However, the user could change the filename if they wish to make it more readable, but the current scheme should remain in my opinion.

**Comment by y20k** [comment]
Track selection is now implemented. A delete option is already planned (see [TrackFragment.java#L179](https://github.com/y20k/trackbook/blob/0eaaf55f757c8a0e2db560facad9d6210ce2a156/app/src/main/java/org/y20k/trackbook/MainActivityTrackFragment.java#L179)).

I guess I can close this issue.
