### ISSUE TITLE
Add option to change units

### ISSUE THREAD

**Issue by collectorgeneral** [y20k/trackbook#12]
Hello there!
I have been using the app for a while now without too many issues, and asking a few friends to use it too!
When me and my friend compare our walking routines, I noticed that my friend has the distance recorded in feet (needless to say they are from the U.S) where as I have it in metres. How does the app determine what units to use? They were trying to switch to a more sane system 😉, but seems like there is no option to do so.
So the obvious request is, would it be possible to add it to the app? Perhaps add an 'Options' in the menu thing. If in the future you end up adding more features, they can go in there. For the time being, if you can add the option to switch between systems, it will be great!

**Comment by y20k** [comment]
The app checks the settings of the device... the so called LOCALE. On Android this values is set implicitly by the language settings. So if you have chosen in Android Settings one of the languages spoken in one of the countries (still 😸) using imperial units, Trackbook will display distances in feet.

As to your suggestion. It is a bit of a spleen of mine ... but I really like apps that are simple enough that they do not need an Options menu. That is why I implemented the LOCALE-check ... to not need to offer an Options menu.

Lets see how long I can hold that idea up :-)

**Comment by collectorgeneral** [comment]
I was suspecting as much, it would make sense that the units match the locale. I understand the KISS principle, and perhaps its best left that way 😄.
To solve this problem without the options menu, you can simple display both where ever you are displaying distance. If you can detect what units are being recorded, conversion is a trivial task. Then just display distance in metres, while showing the distance in feet in brackets. 
I am not sure if it is all worth it though, especially if this can be accomplished with a simple change in language. I'll leave it up to you to decide 😄

**Comment by y20k** [comment]
Good idea. I am trying to implement it right now. I have to look out so that the unit-switch gesture does not interfere with the swipe up/down gesture for the statistics.

**Comment by Hob111** [comment]
If this can be implemented could the *imperial* units be displayed in miles rather than feet? Whereas most of us can divide by 1000 to get from m to km many people find it a challenge 🤔 to divide by 5280 in their heads. 2 decimal places ought to suffice.

**Comment by y20k** [comment]
Hi there. To be able to test the tap gesture I switched my phone to US-English and I see the problem you have. I have opted to use [NumberFormat](https://developer.android.com/reference/java/text/NumberFormat) to make longer numbers more readable (see [LengthUnitHelper.java#L53](https://github.com/y20k/trackbook/blob/dec46976b18f1439aac996d5a2d78c7fe8bfbab5/app/src/main/java/org/y20k/trackbook/helpers/LengthUnitHelper.java#L53).

You can see the results in those screenshots below. I might consider to display miles / kilometer for tracks longer than ... lets say 5 km? But I think for now NumberFormat solves the readability problem. 

## Initial state (US-English and other Imperial locales)
![2018-05-03-10 23 08](https://user-images.githubusercontent.com/9103935/39567183-5f6c3bfc-4ebe-11e8-9be9-70db6c5bf0ec.png)

## ... user taps on the statistics sheet
![2018-05-03-10 23 20](https://user-images.githubusercontent.com/9103935/39567190-62ac2e26-4ebe-11e8-833d-6570588f76e2.png)

**Comment by Hob111** [comment]
Hi again, I should explain that I'm actually from the UK so my app is by default set to metric. If you've ever visited the UK you'll know that despite having adopted metric units aeons ago we still use a rag bag of units. For example, we buy petrol in litres but all our road signs are in miles and miles per hour! We therefore tend to think in miles (at least when you're as old as me!), so an ability to switch the display temporarily from metric to *imperial* would be invaluable. However, we wouldn't normally express a distance of over a mile in feet. Maybe they do in the US?

**Comment by y20k** [comment]
Hi there. I think that the tap gesture is not the best solution for that. Most of the users from countries with metric units do not care to see the imperial equivalent. What do you think? Should I include England in the list of "Imperial" countries? Are feet/miles the common way to measure length in England? I am not familiar with the matter. I just searched Wipedia for countries that officially use the Imperial system.

**Comment by Hob111** [comment]
Ah, now I think I understand better, you are proposing to set up the tap gesture so that those with *imperial* measurements as default can see the metric equivalents, you aren't proposing that it should work both ways. That makes sense. I'll consult my daughters to get a young person's point of view on what units they usually use to measure distance and get back to you. I wouldn't want to incur the wrath of most other UK users. (BTW - thanks for implementing the Resume feature.)

**Comment by y20k** [comment]
> get a young person's point of view 

That seems to be very good approach :smiley:

**Comment by Hob111** [comment]
Daughters and their friends use miles for distances more them a few hundred metres, simply because the UK never adopted km and km/h when it metricated. They don't use feet or yards (0.91 m) and use inches only if they're more convenient than cm. So they use metric units most of the time and therefore it doesn't seem appropriate to include the UK in the list of countries using *Imperial* units. Additionally, our maps have contours marked in metres and use a grid reference system based on 1km squares, and finally it would spoil some elegant programming - **exceptions are evil!**

One final plea. I note if you tap on the elevation data in the statistics you get a toast about the accuracy of the elevation data. Would it be possible to pop up the distance in miles following a tap or long press on the total distance? This shouldn't bother wholly metric users at all whilst helping we metrically challenged.

**Comment by y20k** [comment]
Thanks for your research! Here is what I did (see [commit](https://github.com/y20k/trackbook/commit/eda489e42853e14dd15aafcec53837a16d2faaeb)): 

* I kept the metric system for devices configured to British english
* on those devices I added the unit switch (tap to see miles) - other countries using the metric system do not get this
* distances over one kilometer (and over one mile) are now displayed as km (or mi)

> exceptions are evil!

Very true, but in this case it was easy to implement

I will roll out the changes probably next week - depending on my schedule.

**Comment by y20k** [comment]
Forgot to close this issue. Units now can be switched on tap as described earlier.
