### ISSUE TITLE
History of tracks

### ISSUE THREAD

**Issue by quite** [y20k/trackbook#2]
This looks great! Finally a no-nonsense, no-login track logger. Looking forward to be able to keep a history of my tracks on the phone

**Comment by y20k** [comment]
> history of my tracks

Yeah. I want that, too. 

First step will be a dual tab interface. One tab for the map, and one for the last track. I am already experimenting with this. 

<img src="https://cloud.githubusercontent.com/assets/9103935/18618326/cc0af976-7de4-11e6-9167-7936c84476b6.png" width="180">

Next step then could be a dropdown on the last track tab for the last 10 tracks. Since I want the app to be dead simple I guess I won't do a track management. Last 10 tracks should be enough.

The next couple of releases will focus on bug fixing. But the feature "last track" (and subsequently "last ten tracks") is on its way.

**Comment by goopen** [comment]
Hi,
I like this feature aswell. I think its sad If its limited by only 10 last tracks. I'd opt for this to be configurable, and output it in json or something. :)

**Comment by y20k** [comment]
Hi @goopen , 

I guess I will tackle the problem one step at a time. I want to start with just one track and see how it goes from there. Next step will be ten tracks. For more tracks I need an idea for a dedicated user interface for handling tracks.

Trackbook will store past tracks as files on the device's external storage - and (for my convenience) I will probably use JSON ([google-gson](https://github.com/google/gson)) as a format. (see [`StorageHelper.java`](https://github.com/y20k/trackbook/blob/deed2f624d93590c4929682839fae6c367684497/app/src/main/java/org/y20k/trackbook/helpers/StorageHelper.java#L90)).

Anyway. This can take a while. I am only working on this in my free time. But since I am a heavy user of Trackbook myself and since I really want to see my past tracks, I will definitely implement the feature.

**Comment by y20k** [comment]
Just a short update. I am making progress. Although admittedly a bit slow. But keep in mind. I am alone and I am doing this only in my free time.

<img src="https://cloud.githubusercontent.com/assets/9103935/18995402/49a82eb2-872c-11e6-9cba-b6e859dd228d.png" width="180">

**Comment by collectorgeneral** [comment]
@y20k 

Hello, I found your app simple and interesting, almost everything I am looking for! I have a few suggestions on this very topic, and I hope they are not overly complicated!

-  I love the app, but I really want to access and share my travel history. It would be nice if the history of my travel was stored indefinitely. which I can then retrive on demand. 
Can I suggest you use the GPX file format to store previous locations? This is cross compatible with other apps and such. Either way, as long as the data is accessible, I think I am fine. (It would be nice to import/export the data in and out of the app as necessary). 

- I like your tabbed approach! I want to suggest calling the second tab 'History' and ask the user to input a custom date range perhaps? I am not sure how you can go about doing that, but say I want to access last week's data, or the first Tuesday of last month, it would be nice if you could specify that in this tab and get to see the data points and the usual information. 

Let me know what you think!

**Comment by y20k** [comment]
Hi @collectorgeneral ,

I am a bit time-constraint at the moment. The development of Trackbook is happening - but a slow pace. 

- The next release will only offer to save **one** track.
- The release after that will feature displaying **multiple** tracks

After that I am not sure. Deleting and or Favoring tracks would be an option. And Sharing is definitely an option that I would like to have myself. Internally Transistor stores tracks as JSON. I guess I could offer an export to GPX somehow. GPX does not store metadata like "steps taken", as far as I know. Sharing to Twitter or Whatsapp would be another nice option to have.

**Comment by y20k** [comment]
some more dev screenshots

![2016-12-05-16 58 45](https://cloud.githubusercontent.com/assets/9103935/20895505/0c4b58d8-bb1a-11e6-982f-ac382b8f9bf8.png)
![2016-12-05-16 58 56](https://cloud.githubusercontent.com/assets/9103935/20895506/0c5233d8-bb1a-11e6-8a7e-217f25ad9964.png)

**Comment by collectorgeneral** [comment]
@y20k 

I understand that the development will be slow, I am ok with that :). Though I cannot help you with the code (since I am not a coder), I can and will help you in other ways as much as I can!

- (I think you meant Trackbook, not Transistor 😄) Yes, I think having multiple Import/Export options would be great, so users can export to JSON or GPX, depending on their needs. My primary reasons for the export is to 
  - Backup the data to avoid losing it in case of problems (Example: I need to reset my phone due to some issues). 
  - To load it on to my PC and look at the maps when I need to. 
- If I can achieve that same with JSON, then it won't matter to me if it is GPX or JSON  (though I am not  sure how to use JSON formats on desktop. If you can guide me on that, I would appreciate it). 
- I think I remember reading somewhere that you can save some metadata in the GPX file, though I could be really off. I will try digging around some older projects I contribute to, to see if I can get this info. Do not rely on this bit of info though, my memory is rust at best.
- After implementing indefinite history save/export/display/load, favourite or share would be great too!

 If you want me to help you in testing dev releases and report bugs or anything, please let me know :).

**Comment by y20k** [comment]
> If you want me to help you in testing dev

Thanks. I will might actually take you up on your offer in the future.

**Comment by collectorgeneral** [comment]
>>     If you want me to help you in testing dev

>Thanks. I might actually take you up on your offer in the future.

Sure thing. Just put a message here when you need me to test the releases.

**Comment by y20k** [comment]
I made some progress today. I think figured how the handle to "save" and "clear" actions with minimal user interaction and no additional buttons. (see [commit](https://github.com/y20k/trackbook/commit/f3909ec3a54decb7afd4f9b71baba56fc4ad6267)). That was actually very easy - in hindsight.

![2016-12-12-17 53 07](https://cloud.githubusercontent.com/assets/9103935/21110256/c51df5dc-c09c-11e6-8c44-19eca7d8fcec.png)

**Comment by collectorgeneral** [comment]
@y20k 
That appears to me like a great idea! 
I assume next step is to display the saved data along with import/export.

**Comment by y20k** [comment]
After tapping "Save and Clear" ...

1) the map is cleared / empty again 
2) the track is saved to storage using [GSON](https://github.com/google/gson)
3) the app switches to the second tab with the saved track- pictured above.

The upcoming version already saves ten tracks as files to the phones storage behind the scenes. 

The version after that will feature a track switcher - probably a dropdown so that you can review more than just one last track. But as you can see development is slow right now, since I am short of time.

A note aside: an one hour recording takes up circa 100kb on storage.

**Comment by collectorgeneral** [comment]
100KiB/Hour? Not a huge deal I think (About 30MB/Month assuming a roughly 12 Hour usage per day).  I would suggest you to save the files in a format like (yyyymmdd_hhmm.json) or something. It will make life easier when trying to find data from possibly 100's of files!

For the display part, I will just remind you that user may move the data in and out. So your list may have to be updated everytime it is called to see what files are present. If you can do that with your drop down idea, then thats great too. 
If you cannot, then alternatively, you can have a Pane on one side of the window (kinda like a file browser), that will allow user to select the file they wish to view.

**Comment by y20k** [comment]
> About 30MB/Month 

You are right. 100kb is not much.  I could increase the number of saved tracks.

> assuming a roughly 12 Hour usage per day

That is a pretty hardcore usage scenario 🚀😄

**Comment by y20k** [comment]
I think Trackbook v1.0.0 is now ready to go. A few minor things are missing - like new screenshots for Google Play and an updated how-to description. 

Quite a lot has changed since v0.9.5 (code-wise) - so I do expect (minor) bugs. That is why I will wait with an official release until after Christmas. (= not interested in bug fixing during that time.)

If anyone is interested in testing in the meantime. Here is a signed preview release: [trackbook-app-test-1.0.0a.apk](https://www.dropbox.com/s/owcpvmw3nqy5nwe/trackbook-app-test-1.0.0a.apk?dl=0). This version is based on the current code including [commit  d5b4d9b](https://github.com/y20k/trackbook/tree/d5b4d9b8c236f4ab9d466bd55b6dc2550da3894f).

This version saves up to 25 tracks as JSON/Plaintext in the user accessible directory /Android/data/org.y20k.trackbook/files/tracks . Only the last track is displayed in the UI at the moment.

**Comment by collectorgeneral** [comment]
I can do the testing part. I will open a new issue if I find any bug(s), which you can fix after christmas :).

**Comment by y20k** [comment]
Thanks. It would be great if you could give the app a test run! 👍

**Comment by y20k** [comment]
I will close this issue - Let's continue the discussion in #10
