### ISSUE TITLE
The Italian translation does not work

### ISSUE THREAD

**Issue by marcoM32** [y20k/trackbook#23]
The Italian translation is not loading even if the device is configured for the Italian market. Do you have an idea for fix this problem?

**Comment by y20k** [comment]
If I switch the language to "Italiano", the user interface is in Italian (Nexus 5, Android 6). I wonder what you are doing differently.

![2017-08-06 22 22 20](https://user-images.githubusercontent.com/9103935/29006717-e5854938-7af5-11e7-9332-9b945cda97a4.png)

**Comment by marcoM32** [comment]
On my phone (Zenfone 2 Laser) continuing to not work..

**Comment by y20k** [comment]
The folder and file containing the Italian language version( [/res/values-it/strings.xml](https://github.com/y20k/trackbook/blob/master/app/src/main/res/values-it/strings.xml)) have been created by the Weblate service. The strings.xml file  on my local system is UTF-8 encoded. Everything seems to be fine.

Do you use an app whose developers also use Weblate (see https://hosted.weblate.org/projects/)? If so, do you have similar problems with one of those apps?

And: which version of the app you have? Italian is part of the app since  v1.0.5. I just noticed that F-Droid still has listed v1.0.4 as the latest version.

**Comment by marcoM32** [comment]
The problem was in the version of the app, downloading from GitHub the version 1.0.5 I solved the problem.

NB: I found some errors in my translation, I will correct them as soon as possible.

Regards
Marco
