### ISSUE TITLE
App crashes on clicking Resume and Clear options simultaneously

### ISSUE THREAD

**Issue by neupanedipen** [y20k/trackbook#35]
#### Expected behavior<br>
The app must be stable and should resume the paused recording and clear the record on clicking the Resume and Clear options.<br>
#### Actual behavior<br>
But the app crashes on clicking Resume and clear option simultaneously and immediately.<br>
#### How to reproduce<br>
1. Install the app from fdroid.<br>
2. Launch the app. Turn on the location services of your device.<br>
3. Clicking on blue button to start tracking. Click on it again and it will pause the tracking. On clicling on it again will shoe you three options (Resume, Clear and Save) Click on Resume option.<br>![](https://s19.postimg.cc/dwy6u5xwz/20180519_235252.png)
4. Click on the blue button again and click on Clear option.<br>
5. Click on the blue button again. The app crashes.<br>
* App Version: 1.1.8<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/H-gvLX5ssQA

**Comment by y20k** [comment]
Thanks for the excellent bug report!! I will look into it.

**Comment by Hob111** [comment]
I've observed this and can reproduce it. However. the App hasn't exited, it has just reported a stop and "minimised" the window. The App still seems to be running and fully functional as far as I can ascertain, so the error seems to be in reporting an error when there isn't one or in reporting a non-fatal error as a crash. if you see what I mean 😕 🤔 . No data are lost because the user has just cleared them!

**Comment by y20k** [comment]
the next release will fix this bug. thx
