### ISSUE TITLE
how to replace line instead circle point?

### ISSUE THREAD

**Issue by mahdi00021** [y20k/trackbook#41]
![download 1](https://user-images.githubusercontent.com/9013165/44297933-06d05480-a2ef-11e8-98be-d4a75d35e59e.jpg)
I want that addline between points and connect points with line 
help me

**Comment by y20k** [comment]
Hi there. I cannot help you, because I did not research how to do that. I am using osmdroid to draw the map in Trackbook. It is probably better to research the documentation for osmdroid - and if that does not help, you could direct your question directly to the osmdroid developers.

--> [osmdroid](https://github.com/osmdroid/osmdroid)

**Comment by mahdi00021** [comment]
thanks
how to do i create script php backend?

**Comment by Hob111** [comment]
This isn't a scripting help forum. I suggest you put "script php backend" into a search engine, there are loads of hits.

**Comment by mahdi00021** [comment]
Is it possible that create backend PHP for this app?
