### ISSUE TITLE
App is crashing

### ISSUE THREAD

**Issue by paulle** [y20k/trackbook#45]
App crashes.
Android 9, Sony xz2

**Comment by y20k** [comment]
Hi @paulle, 

you are probably experiencing the bug described in #44. Please install the latest version and delete any problematic files - possibly all recordings since Wednesday 31/10/2018. You will find those files here: `/Android/data/org.y20k.trackbook/files/tracks`

Latest release:
* [v1.1.12](https://github.com/y20k/trackbook/releases/tag/v1.1.12) here on GitHub
* and on [Google Play](https://play.google.com/store/apps/details?id=org.y20k.trackbook) should be on F-Droid in a couple of days, too.

I am terribly sorry for any inconveniences.

**Comment by paulle** [comment]
Thank you for the fix. I downloaded v1.1.12. Could only try it for some minutes, seems the crashes are fixed. Will try it later wit more time and do another install when it's on f-droid.

**Comment by y20k** [comment]
v1.1.13 is out on [F-Droid](https://f-droid.org/en/packages/org.y20k.trackbook/). v1.1.13 fixes #44, which is related to this issue.
