### ISSUE TITLE
Wrong distance

### ISSUE THREAD

**Issue by paulle** [y20k/trackbook#46]
Showing wrong distance. Trackbook is showing wrong distance. A record is showing a distance of 188 km. Maybe the real distance was 1,8 km.
I'm using the German version. Maybe the error is because in Europe the decimal sign is a comma and in the US is a dot.

**Comment by y20k** [comment]
Hi there. Thanks for reporting this. Can you do me a favour and zoom out. Maybe there is a recorded dot way off.

**Comment by paulle** [comment]
![screenshot_20181105-174221](https://user-images.githubusercontent.com/4852079/48054099-ba3d3c80-e1ac-11e8-9103-00dd9554bc89.png)
This record was during a short bus ride, 188km in two ninutes.

**Comment by Hob111** [comment]
Those red dotted lines don't look like track points, I think they're part of the map.

On an "active" track (one that's being recorded) the track points are red spots. On a saved track the points are blue spots. If you pan out you should find a spot, possibly grey not blue, plotted about 188km away. Another thing you could try is to export the track as a .gpx file and post it here. You could also try displaying it on a web site than joins the points. This one works for me but I'm not sure how it will cope with a location in Germany. The OSM map should be OK.

http://www.bikehike.co.uk/mapview.php

May I suggest you go to Issue #44, download and install trackbook-app-testing-1.1.13-002.apk which in my experience solves the issue you're experiencing.

**Comment by paulle** [comment]
I installed the trackbook-app-testing-1.1.13-002.apk. But no luck, the app closes immediately after starting.

**Comment by Hob111** [comment]
Very odd, I've been running that version since it was published without any problems and have successfully recorded 3 tracks.  

1. I assume you un-installed the last version before installing this one?
2. Do you have any old tracks on your phone? (In /Android/data/org.y20k.trackbook/files/tracks)
3. What version of Android are you running? I'm using 8 (Oreo).

**Comment by paulle** [comment]
Thank you for your advice.
I downloaded v1.1.12 again and installed it. Could only try it for some minutes, seems the crashes are fixed. Will try it later with more time and do another install when it's on f-droid.
Today I've to stay at home, will test when I go out how the tracking works.
I'm using android 9.

**Comment by Hob111** [comment]
I'm very puzzled, I'm running trackbook-app-testing-1.1.13-002 on two phones, Android 6 and 8, and both are working perfectly. I can't imagine there is a problem with Android 9 but it seems to be the only difference. (Since you didn't reply to my points 1. and 2. above I'm assuming the answer was yes to 1. and no to 2.)

Are you installing v1.1.12 from the Play Store or using the .apk on Github? (like you I prefer to use F-Droid whenever possible).

**Comment by paulle** [comment]
@Hob111 I'm running trackbook-app-testing-1.1.13-002 from github. But i had to delete and reinstall it two to get it running. Don't now why. And both times I deleted /Android/data/org.y20k.trackbook/files/tracks too.
But now trackbook is running o.k.
When the next version is on f-droid, I will install again install it from there.

**Comment by Hob111** [comment]
@paulle What a relief, :relieved:,  I was beginning to think there was some mysterious problem with Android 9.
Don't install v1.1.12 from F-Droid, it's the same as v1.1.10. @y20k did a roll-back to the 1.1.10 code to solve quickly a serious issue with v1.1.11 (see #44 for the full story). I'm sure when he's satisfied that trackbook-app-testing-1.1.13-002 is working properly (and he has time after he's done his proper job :smiley:) he'll publish it as v 1.1.13, so look out for that.

**Comment by paulle** [comment]
@Hob111 Don't worry, will wait for updating till 1.1.13 or higher is on f-droid. Thanks for your help.

**Comment by y20k** [comment]
Hi @paulle & @Hob111 ,

Today I published [v1.1.13](https://github.com/y20k/trackbook/releases/tag/v1.1.13). This version brings back the fix for the imprecise location fix at the start of a recording (see #21) - minus the bug v.1.1.11 introduced.

F-Droid should automatically grab the source code and compile an APK which in turn you can install on your devices. But: As of now F-Droid still has the buggy version v1.1.11. I need to investigate that.

**Comment by y20k** [comment]
FYI https://gitlab.com/fdroid/fdroiddata/issues/1435

**Comment by y20k** [comment]
v1.1.13 is out on [F-Droid](https://f-droid.org/en/packages/org.y20k.trackbook/). This one fixes #21 and #44 and probably this issue, too. If not, please re-open.
