### ISSUE TITLE
Speed color coding

### ISSUE THREAD

**Issue by hockeymikey** [y20k/trackbook#55]
Building off of #42 alittle, have a setting to color code the dots/lines based on how fast they are going. Give people the ability to customize what colors it will use and for what speeds in a simple list.

**Comment by Hob111** [comment]
There is an app that attempts to do this. "Simply Walking" available from Play Store. It doesn't really come off, I think because it's influenced by the errors in GPS location on a phone. To make it work you'd need to interpolate quite a few points. It would be quite a bit of code for not very much gain imo.

**Comment by y20k** [comment]
@hockeymikey I am a bit undecided on drawing lines instead of dots on the map (see #42). 

But colored lines indicating speed? I think that may lead to problems - and not be worth the coding.

- confusion. users maybe confused by the meaning of the colors. I would need to add a map legend
- settings. I don't like settings :wink: 
- accuracy. Trackbook records a waypoint every ten seconds. GPS fixes are often not too accurate, speed may vary from waypoint to waipoint considerably.
- colors. Should colors be: (1) tied to certain fixed speeds or (2) be assigned relatively on a per track basis. Both solutions have different positive and negative implications.

**Comment by y20k** [comment]
Same as #56 (Path editing): I will leave this issue open for discussion, but don't be disappointed, if I eventually close it.

**Comment by hockeymikey** [comment]
@Hob111
There's no source code so not interested in that alone, plus I like this project better. The lines just connect the dots, would hardly be a difference, and you could just make a path of best fit if one wanted too, that wouldn't be hard.
@y20k 
They wouldn't because the setting is optional and off by default. Further, users can configure the color based on speeds to maybe between 5-10mph is green let's say or whatever color they want.

Why don't you like settings?  Do you find it hard making the activity for it or have some unseated vendetta against shared preferences or sqlite databases.

They could, but honestly shouldn't be that bad.  Could smooth it out over multiple ones. Also, why isn't there a setting for the interval for waypoint collection?

Now this last one is actually a thinker. I'm not sure, I was thinking just a default throughout the app, but defining multiple speed palettes and defining them per track would be easy too.

**Comment by Hob111** [comment]
@hockeymikey I cited "Simply Walking" as an example of why this is very difficult to implement in a meaningful way, Try that app and you'll see why. I believe what you are suggesting is impractical.

**Comment by y20k** [comment]
I am closing this issue. But since I think this is/was an interesting discussion I created an Issue that collects "[Previous discussions and feature requests](https://github.com/y20k/trackbook/issues/57)".

I have a similar pinned [Issue](https://github.com/y20k/transistor/issues/48) in my other project Transistor.

**Comment by hockeymikey** [comment]
@Hob111  Probably won't because it's not hard to implement, and I don't really care about wasting my time with others are doing when I have the vision already.
