### ISSUE TITLE
Measurement enhancement

### ISSUE THREAD

**Issue by marcoXbresciani** [y20k/trackbook#62]
In saved track statistics, the total distance is shown in kilometres (at least on my phone, not sure about miles). It would be nicer (and more fine) to have it in actual metres, if available. Or both,. :)

So, for example, this morning it says I walked 3,4km. But it's 3400m or 3499 or something in the middle? :)

**Comment by Hob111** [comment]
On my phone track distances are reported in km to 2 decimal places (ie to +/- 5m assuming normal mathematical rounding is used). Surely that is good enough for anyone? GPS location on a phone is accurate to within about 3m at best and is often much poorer than this in areas with high buildings or a lot of trees, so more figures simply aren't justified because mathematically they're not significant.

There is the odd occasion when a track is only reported to 1 decimal place. I assume this means that the second place is 0 (zero) which for some reason isn't displayed.

**Comment by y20k** [comment]
Having longer distances measured in meters would impact the readability of the screen. I think it is best to leave it as it is. And I think @Hob111 is right: Trackbook's results are not precise enough.
