### ISSUE TITLE
v1.2.2 vs v2.0.2

### ISSUE THREAD

**Issue by Hob111** [y20k/trackbook#68]
These are maybe questions with a simple yes/no answer rather than issues.

1. Is v2.0.2 incompatible with Android 6? I have an old phone and a tablet that both run Android 6 and a phone running Android 8. The latter has upgraded to V2.0.2 (F-Droid). The Android 6 devices are stuck on v1.2.2 although the app description on F-Droid is the same for all devices apart from the heading :confused:
![Screenshot_20200320-125239](https://user-images.githubusercontent.com/38910411/77165752-d5130700-6aaa-11ea-85b0-06f8ac687651.png)

2. I discovered to my dismay that v1.2.2 (and earlier) only keeps 25 tracks and then deletes them automatically on a FIFO basis. Does the :star: feature in v2.0.2 prevent this behaviour? If not then would it be possible to put the deletion of tracks under the control of the user?

**Comment by y20k** [comment]
Hi @Hob111 

hope you are well.

> v1.2.2 (and earlier) only keeps 25 tracks. 

I know, that is not ideal. I had to put in a limit, because the performance of the drop-down menu, that lists all your recordings, is not good. There is a short mention in [README.md](https://github.com/y20k/trackbook/blob/v1.2.2/README.md#statistics-and-last-tracks) to my defense. But I know, it would have been better to have warning within the app. The new tracklist in v2 should be MUCH more performant. I did not set any limits here.

> app description on F-Droid is the same for all devices apart from the heading

That seems to be a F-Droid problem. The only thing I do is, I create a [changelog](https://github.com/y20k/trackbook/tree/master/metadata/en-US/changelogs) file for each new version, which F-Droid somehow processes.

> Is v2.0.2 incompatible with Android 6

Yes. I am sorry. I decided cut support for devices prior to Android 7.1. That helps me to better maintain and develop my apps. I know that this is a controversial decision (see Escapepod's [Issue #2](https://github.com/y20k/escapepod/issues/2)). The upcoming release of my radio app Transistor will also cut support for older OS versions. I expect some angry users :-/ there.

**Comment by Hob111** [comment]
Hi @y20k 

We're fine, hope you and your family are well.

Thanks for your reply. I'm pleased to learn that the the latest version now keeps tracks until the user removes them. I don't think I ever lost anything before I'd copied it to my laptop but it came close  :relieved:

Regarding support for Android 6 and earlier, I suspected that was the case and I fully understand the need to set a cut off somewhere. Interestingly F-Droid and Google tackle this in a different way. A search for **Trackbook** in the Play Store using an Android 6 device doesn't find any version whereas F-Droid behaves as I describe above - I think I prefer that.

One final question about v2.0.2 before I close this issue. The settings now include an _Accuracy Threshold_ which by default is set to 30. Does this number have a unit; is it an absolute value or a  relative value? Some explanation in the app settings menu might be helpful.

Thanks for all your hard work in producing the latest version, it's very much appreciated.

**Comment by y20k** [comment]
I am not sure how to surface help information within the app off the top of my head. Any ideas? Maybe a short "Toast" message bubble when tapping _Accuracy Threshold_ .

The answer to your question would be
==> https://github.com/y20k/trackbook#what-does-accuracy-threshold-mean

Is the answer understandable? Or should I re-phrase it?

**Comment by Hob111** [comment]
I might have known, RTFM :grin:. Having read the documentation I need to think about this a bit more and brush up on my stats. Give me a few days to get my tired, aged brain into gear.

**Comment by Hob111** [comment]
Sorry it's taken me almost a year to get back to this.

What getAccuracy is actually returning is _sigma_, which is the standard deviation, a statistical parameter.

As the documentation explains, if you draw a circle of radius _sigma_ around the reported location then there is a 68% probability (actually 68.27%) that the true location lies within this circle. Of course, it also means that there's a 32% probability (_ie_ 32 out of every 100) that the true location lies outside this circle.

If you use multiples of sigma then the certainty one can attach to a value increases. 

Thus if you draw a circle of radius 2 x _sigma_ around a reported location there is a 95.45% probability that the true location lies within this circle.

Draw a circle of radius 3 x _sigma_ around a reported location and the probability rises to 99.73%

This is pertinent to the discussion at #96

**Comment by Hob111** [comment]
Superseded by #96 . Closed.
