### ISSUE TITLE
Anybody has APK for version 1.2.2

### ISSUE THREAD

**Issue by poet-man** [y20k/trackbook#80]
Hello there,
as I learned, that Trackbook versions had bin cut off for older configurations, but I still would like to use TB on my Android 7 Samsung Galaxy, I ask arround, whether anybody still has an APK for version 1.2.2. Or knows a source for it?
Of course it's not supported anymore, but it worked on my device (nearly) absolutely fine. I had to setup my device again, and of course cannot find TB in PlayStore anymore.
I would appreciate any information very much (and of course use that old version at my own risk; but as anybody can surely guess, I don't want to buy a new smartphone with latest Android, to be able to use TB again; on my tablet version 2.0.6 runs ok)

**Comment by Hob111** [comment]
Afaik Android 7 is fine for the latest Trackbook. I think the cutoff is 6 and below. 
-- 
Sent from my Android phone using K-9 Mail.

On 7 September 2020 09:40:25 BST, poet-man <notifications@github.com> wrote:
Hello there,
as I learned, that Trackbook versions had bin cut off for older
configurations, but I still would like to use TB on my Android 7 Samsung
Galaxy, I ask arround, whether anybody still has an APK for version
1.2.2. Or knows a source for it?
Of course it's not supported anymore, but it worked on my device
(nearly) absolutely fine. I had to setup my device again, and of course
cannot find TB in PlayStore anymore.
I would appreciate any information very much (and of course use that old
version at my own risk; but as anybody can surely guess, I don't want to
buy a new smartphone with latest Android, to be able to use TB again; on
my tablet version 2.0.6 runs ok)

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/y20k/trackbook/issues/80

**Comment by poet-man** [comment]
Have found apk for 1.2.2 via Google and installed again.
In thread postet by y20k earlier, he said, support was cut off prior to Android 7.1.
Having 7.0 on my work-smartphone with no possibility to upgrade, it's not supported anymore.
I wonder if system requirements are visible in app at prominent point, but maybe it's my fault and I just didn't see it.

**Comment by y20k** [comment]
https://github.com/y20k/trackbook/releases
