### ISSUE TITLE
"Unable to save. Please install a file manager first" even if file managers are installed

### ISSUE THREAD

**Issue by AlexanderRitter02** [y20k/trackbook#81]
### The bug
When clicking on the save button, the following error message appears:
> "Unable to save. Please install a file manager first"
<img src="https://user-images.githubusercontent.com/42546705/92642338-53c16200-f2e0-11ea-8111-27107193bc1e.png" width="250" />

Even though I have *two file managers* installed:
- OnePlus default file manager
- [FX File Explorer](https://play.google.com/store/apps/details?id=nextapp.fx&hl=de)

Strangely enough, a few months ago, I didn't have this problem occur.
I recently started using it again and stumbled upon this bug. I am not able to find out whether the cause is the new Trackbook version or my OnePlus device.

Thanks in advance for looking into this and of course for developing this useful utility.

### Expected behaviour
To detect installed file managers properly.

1. If multiple file managers exist, open an Android app selection dialog , allowing to choose one as default or one-time

     > **Reference example** (but with file managers)
     >    <img src="https://user-images.githubusercontent.com/42546705/92643376-f29a8e00-f2e1-11ea-8605-20aa0b5bb637.jpg" width="250" />
2. If only one file manager is available, to open in that app

### Additional Information
**Device:** OnePlus Nord
**Android version:** 10
**Distribution:** Oxygen OS 10.5.6.AC01BA

**Trackbook version:** 2.0.5 ("Echoes") from F-Droid

**Comment by y20k** [comment]
Hi. Thanks for reporting this bug. A similar error came up a while ago (see [Issue 70](https://github.com/y20k/trackbook/issues/70#issuecomment-607313049)). Any chance that you disabled one of the file managers?

**Comment by wagu1** [comment]
Using android11 there is no file manager anymore. I install F-File-Manager, but trackbook did not recognize it. So I can't save my gpx-data to a different place. Some version before it was possible to export data direct to nextcloud or a messenger - that was a great feature. Is it possible to implement this feature again?
Thanks for a great tracking-app.

**Comment by y20k** [comment]
Thanks. Android 11 seems to be a good direction to investigate. I will check what can be done here.

**Comment by y20k** [comment]
Found the bug. It was an check for the presence of a file manager, that was introduced in #70.

I removed the check since it seems that from Android 11 - or maybe even from Android 10 - on it is not necessary to have file manager anymore. I need to investigate that further.

Anyway... The next version of trackbook ([v2.0.6](https://github.com/y20k/trackbook/releases/tag/v2.0.9)) will fix this problem here - I just need to test, how I can prevent the crash described in #70 differently.

**Comment by wagu1** [comment]
Hello
even after updating trackbook to version 2.0.8 i can't export my gpx file. Android 11 seems to prevent this, under Android 10 it still worked. To my knowledge this is what Google wants. Maybe you can set up a "Share" option that allows you to export the gpx file directly to another program, e.g. nextcloud. Without processing the gpx-file the very nice program makes less sense.

**Comment by Hob111** [comment]
I second this request. The share feature disappeared after the Kotlin rewrite, so now it's a 2 stage process to transfer tracks to my PC where I keep an archive. A share option would make things much quicker and more straightforward.

**Comment by y20k** [comment]
I removed the share feature since it did not work reliably for me. Especially the share action that lets you save the GPX did not work. I could not find out, where the error was. 
Since not everyone has an GPX app on their phone I figured that at least the save feature should work. That was the reason to replace the share feature with the save feature.
But since I generally like the share feature better I will create an extra issue for that and flag it as `help wanted`.

**Comment by y20k** [comment]
see #90

**Comment by Hob111** [comment]
That's odd, I never had any issues with the share feature but then I don't think I ever tried to use it to save to the local device. My use was to copy the gpx track to my PC using this app 

https://github.com/jimmod/ShareToComputer

Or to mail it to other people using K-9 mail.
